(part "TLV62595DMQR"
    (packageRef "TLV62595DMQR")
    (interface
        (port "1" (symbPinId 1) (portName "EN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PG") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SW") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VIN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV62595DMQR")
    (property "Mouser_Part_Number" "595-TLV62595DMQR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV62595DMQR?qs=IS%252B4QmGtzzrUF%252B1uc1ZRLQ%3D%3D")
    (property "Arrow_Part_Number" "TLV62595DMQR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tlv62595dmqr/texas-instruments?region=nac")
    (property "Description" "Conv DC-DC 2.5V to 5.5V Synchronous Step Down Single-Out 0.6V to 4V 4A 6-Pin VSON-HR T/R")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/tlv62595.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1622796971373&ref_url=https%253A%252F%252Fwww.digikey.in%252F")
    (property "symbolName1" "TLV62595DMQR")
)
