(part "DFE252012P-2R2M_P2"
    (packageRef "DFE2HCAH1R0MJ0L")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "DFE252012P-2R2M=P2")
    (property "Mouser_Part_Number" "81-DFE252012P-2R2MP2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/DFE252012P-2R2M%3dP2?qs=KuGPmAKtFKXLyjzo39FSsQ%3D%3D")
    (property "Arrow_Part_Number" "DFE252012P-2R2M=P2")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/dfe252012p-2r2mp2/murata-manufacturing?utm_currency=USD&region=nac")
    (property "Description" "Toko DFE252012P Series Shielded Wire-wound SMD Inductor with a Powered Iron Core, 2.2 uH Wire-Wound 3.4A Idc")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02/J(E)TE243A-0024.pdf")
    (property "symbolName1" "DFE252012P-2R2M_P2")
)
